---
apiVersion: v1
kind: Service
metadata:
  name: snyk-juice-shop
  labels:
    app: snyk-juice-shop
spec:
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
  selector:
    app: snyk-juice-shop
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-juice-shop
  labels:
    app: snyk-juice-shop
spec:
  selector:
    matchLabels:
      app: snyk-juice-shop
  replicas: 1
  template:
    metadata:
      labels:
        app: snyk-juice-shop
    spec:
      containers:
      - name: juice-shop
        image: rajohnston/juice-shop:0.1.20
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        securityContext:
          privileged: true
