---
apiVersion: v1
kind: Service
metadata:
  name: snyk-juice-shop:0.1.4
  labels:
    app: snyk-juice-shop:0.1.4
spec:
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
  selector:
    app: snyk-juice-shop:0.1.4
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-juice-shop:0.1.4
  labels:
    app: snyk-juice-shop:0.1.4
spec:
  selector:
    matchLabels:
      app: snyk-juice-shop:0.1.4
  replicas: 1
  template:
    metadata:
      labels:
        app: snyk-juice-shop:0.1.4
    spec:
      containers:
      - name: juice-shop:0.1.4
        image: rajohnston/snyk-juice-shop:0.1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        securityContext:
          privileged: true
